name: Build and deploy

on:
  push:
    branches: [ master, staging, migrate-github-pages ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout the latest code'
      uses: actions/checkout@v2      
      
    - name: 'Inject slug/short variables'
      uses: rlespinasse/github-slug-action@v2.x
        
    - name: 'Update site with run number'
      run: |
        sed -i "s/#BUILD_ID#/${{ env.GITHUB_REF_SLUG_URL }}-${{ github.run_id }}/g" _includes/nav.html
        
    - name: 'Update site with SHA'
      run: |
        sed -i "s/#COMMIT_ID#/${{ env.GITHUB_SHA_SHORT }}/g" _includes/nav.html
        
    - name: Jekyll Build
      uses: jerryjvl/jekyll-build-action@v1
       
    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v3
      with:
        target_branch: gh-pages
        build_dir: /build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
