name: Build and deploy

on:
  push:
    branches: [ master, staging, migrate-github-pages ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout the latest code'
      uses: actions/checkout@v2      
      
    - name: 'Inject slug/short variables'
      uses: rlespinasse/github-slug-action@v2.x
        
    - name: 'Update site with run number'
      run: |
        sed -i "s/#BUILD_ID#/${{ env.GITHUB_REF_SLUG_URL }}-${{ github.run_id }}/g" _includes/nav.html
        
    - name: 'Update site with SHA'
      run: |
        sed -i "s/#COMMIT_ID#/${{ env.GITHUB_SHA_SHORT }}/g" _includes/nav.html
        
    - name: Jekyll Actions
      uses: helaili/jekyll-action@2.3.1
      with:
        # The target branch name the site gets pushed to
        # target_branch: # optional
        # The relative path where the site gets pushed to
        target_path: /_site
      
